import { createDefaultApplicationRouteComposition } from "../services/application-deployment-composition";

export { projectRoutes } from "./projects";
export { projectDashboardRoutes } from "./project-dashboard";
export { projectAdvisorsRoutes } from "./project-advisors";
export { projectNotebookRoutes } from "./project-notebooks";
export { projectSecretsRoutes } from "./project-secrets";
export { projectControlSecretsRoutes } from "./project-control-secrets";
export { projectFunctionsRoutes } from "./project-functions";
export { organizationRoutes } from "./organizations";
export { userRoutes } from "./user";
export { backupRoutes } from "./backups";
export { monitorRoutes } from "./monitor";
export { maintenanceRoutes } from "./maintenance";
export { extensionRoutes, databaseExtensionRoutes, systemExtensionRoutes } from "./extensions";
export { securityRoutes } from "./security";
export { storageRoutes, projectStorageRoutes } from "./storage";
export { storageCompatRoutes } from "./storage-compat";
export { scalingRoutes } from "./scaling";
export { taskRoutes } from "./task-routes";
export { taskEventRoutes } from "./task-events";
export { databaseRoutes } from "./database";
export { databaseJitRoutes } from "./database-jit";
export { authRoutes } from "./auth";
export { authRuntimeRoutes } from "./auth-runtime";
export { wechatAuthRoutes } from "./auth-wechat";
export { chinaAuthRoutes } from "./auth-china";
export { userManagementRoutes } from "./auth-users";
export { authHooksRoutes } from "./auth-hooks";
export { authSsoRoutes } from "./auth-sso";
export { authOAuthServerRoutes } from "./auth-oauth-server";
export { authCustomProviderRoutes } from "./auth-custom-providers";
export { authMfaRoutes } from "./auth-mfa";
export { frontendRoutes } from "./frontend";
export { createApplicationRoutes } from "./applications";
const defaultApplicationRouteComposition = createDefaultApplicationRouteComposition();
export const applicationRoutes = defaultApplicationRouteComposition.routes;
export const applicationPreviews = defaultApplicationRouteComposition.previews;
export { createDefaultApplicationRouteComposition };
export { webhookRoutes } from "./webhook";
export { deployRoutes } from "./deploy";
export { chatRoutes } from "./chat";
export { platformSettingsRoutes } from "./platform-settings";
export { projectLogsRoutes } from "./project-logs";
export { systemRoutes } from "./system";
export { wsRoutes } from "./ws";
export { diagnosticsRoutes } from "./diagnostics";
export { pgredisRoutes } from "./pgredis";
export { logDrainRoutes } from "./log-drains";
export { scheduledFunctionRoutes } from "./scheduled-functions";
export { projectMutationRoutes } from "./project-mutations";
export { branchRoutes } from "./branches";
export { pgMetaRoutes } from "./pg-meta";
export { storageS3Routes } from "./storage-s3";
export { autoBranchingRoutes } from "./auto-branching";
export { projectRbacRoutes } from "./project-rbac";
export { projectWebhookRoutes } from "./project-webhooks";
export { projectAuditRoutes } from "./project-audit";
export { projectEventRoutes } from "./project-events";
export { createProjectCapacityRoutes, projectCapacityRoutes } from "./project-capacity";
export { projectCapabilityRoutes } from "./project-capabilities";
export { projectAuthHookRuntimeRoutes } from "./project-auth-hook-runtime";
export { projectOrganizationRoutes } from "./project-organizations";
export { projectCollaboratorRoutes } from "./project-collaborators";
export { pipelineRoutes } from "./pipelines";
export { databaseWrapperRoutes } from "./database-wrappers";
